const tintColorLight = '#2f95dc';
const tintColorDark = '#fff';

export default {
  light: {
    text: '#13231B',
    background: '#13231BB2',
    tint: tintColorLight,
    tabIconDefault: '#ccc',
    tabIconSelected: tintColorLight,
    screenBackground: '#f9f9f9',
    inputBorder: '#d9d9d9',
    inputPlaceholderColor: '#B1BBC1',
    defaultButton: '#647884',
    defaultButtonText: '#fff',
    activeTabBar: '#263238',
    inactiveTabBar: '#9BA7B1',
    tabBarBackground: '#E8E8EF',
    popupBackground: '#fff',
    bottomPopupHandle: '#b7b7b7',
    white: '#fff',
  },
  dark: {
    text: '#13231B',
    background: '#13231BB2',
    tint: tintColorLight,
    tabIconDefault: '#ccc',
    tabIconSelected: tintColorLight,
    screenBackground: '#f9f9f9',
    inputBorder: '#d9d9d9',
    inputPlaceholderColor: '#B1BBC1',
    defaultButton: '#647884',
    defaultButtonText: '#fff',
    activeTabBar: '#263238',
    inactiveTabBar: '#9BA7B1',
    tabBarBackground: '#E8E8EF',
    popupBackground: '#fff',
    bottomPopupHandle: '#b7b7b7',
    white: '#fff',
  },
  dark_deprecated: {
    text: '#fff',
    subtitle: '#8b8b8b',
    background: '#000',
    tint: tintColorDark,
    tabIconDefault: '#ccc',
    tabIconSelected: tintColorDark,
    screenBackground: '#181A1F',
    inputBorder: '#616161',
    inputPlaceholderColor: '#8f99a1',
    defaultButton: '#87abbe',
    defaultButtonText: '#000',
    activeTabBar: '#d9cdc7',
    inactiveTabBar: '#64584e',
    tabBarBackground: '#262626',
    popupBackground: '#262626',
    bottomPopupHandle: '#0b0b0b',
    white: '#fff',
  },
};
